name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Docker & Docker Compose v2
        run: |
         curl -fsSL https://get.docker.com | sh
         sudo apt-get install -y docker-compose-plugin


      - name: Build with Docker Compose
        run: docker compose build

      - name: Run containers
        run: docker compose up -d
